### ISSUE TITLE
Issue when npm run dist

### ISSUE THREAD

**Issue by hem-sharma** [kslimani/clappr-html5-preroll-skeleton-plugin#1]
![image](https://cloud.githubusercontent.com/assets/15911296/21537575/607818d6-cdb9-11e6-80dd-e7958686dd79.png)

**Comment by kslimani** [comment]
@kaushik-hemant which nodejs version are you using ? _(i suspect you are using an old version like 0.10.x)_

**Comment by hem-sharma** [comment]
Using v0.10.48

Sent from my iPhone

On 29-Dec-2016, at 2:45 PM, kslimani <notifications@github.com<mailto:notifications@github.com>> wrote:


@kaushik-hemant<https://github.com/kaushik-hemant> which nodejs version are you using ? (i suspect you are using an old version like 0.10.x)

-

**Comment by kslimani** [comment]
@kaushik-hemant tha't the reason Promise is undefine. I recommend you to upgrade nodejs at least to latest LTS. Otherwise i think you may need to downgrade some of dependencies. (maybe css-loader)

**Comment by kslimani** [comment]
Also i "googled" that in case you can't upgrade node to latest, it seems that starting from 0.12.x it should work (not tested).

**Comment by kslimani** [comment]
@kaushik-hemant is your issue solved ?
